[package]
name = "zephyr-uart-buffered"
version = "0.1.0"
authors = ["Tyler Hall <tylerwhall@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
zephyr-futures = { path = "../zephyr-futures" }
