[package]
name = "zephyr-uart-buffered"
version = "0.1.0"
authors = ["Tyler Hall <tylerwhall@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.19", features = ["unstable", "read_initializer"] }
zephyr-futures = { path = "../zephyr-futures" }
